//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpaceUnionDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Powerup
    {
        public string PowerupName { get; set; }
        public int PowerupValue { get; set; }
    }
}
