//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpaceUnionDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserStat
    {
        public string userName { get; set; }
        public int userstatWin { get; set; }
        public int userstatLose { get; set; }
        public int userstatShotsFired { get; set; }
        public int userstatHits { get; set; }
        public int userstatKills { get; set; }
        public int userstatDied { get; set; }
        public int userstatShipUsed_1 { get; set; }
        public int userstatShipUsed_2 { get; set; }
        public int userstatShipUsed_3 { get; set; }
        public int userstatFlagsCaptured { get; set; }
    }
}
